---
title: "What Hath Von Neumann Wrought?"
author: "M. Edward (Ed) Borasky"
output: revealjs::revealjs_presentation
---
# Motivation

## Standing on the shoulders of giants

## Born with Curiosity

## This was done with a slide rule

## Archive.org and bitsavers

## The world of Grace Hopper

## The Harvard Mark I

## What was your first computer?

## Did you learn assembler?

## Did you learn machine code?

# John von Neumann

## In Europe

## The Manhattan Project

## Game Theory

## Self-reproducing systems / cellular automata

## Applied Mathematics

## Bureaucrat

## Death

# The IAS Machines

## State of scientific computing

## Preliminary discussions

## Planning and coding

## Hardware

### MANIAC

### JOHNNIAC

### ILLIAC and copies

### IBM 701

### Univac 1100

## Evolution of scientific computers

### IBM 704

### IBM 709

### IBM 7090 / 7094

### IBM 7030

### UNIVAC 1100 series

### CDC 1604

### CDC 6600

### Cray 1

## Evolution of scientific programming languages

### Fortran

### Algol

### Lisp

### APL

### S

### Matlab

### R

### Julia

# The architecture

## Arithmetic unit

```{r echo = FALSE}
library(DiagrammeR)
registers <- create_nodes(nodes = c(
  "Memory", "Accumulator", "Adder", "Quotient", "R3". Complement Gate"),
  shape = "rectangle")
arith_unit <- create_graph(registers)
arith_unit <- add_edge(arith_unit, "Accumulator", "Memory")
arith_unit <- add_edge(arith_unit, "Accumulator", "Adder")
arith_unit <- add_edge(arith_unit, "Adder", "Accumulator")
arith_unit <- add_edge(arith_unit, "Memory", "Quotient")
arith_unit <- add_edge(arith_unit, "Memory", "R3")
arith_unit <- add_edge(arith_unit, "R3", "Complement Gate")
arith_unit <- add_edge(arith_unit, "Complement Gate", "Adder")
render_graph(arith_unit)

```

### Representation of numbers - integers

### Representation of numbers - fractions

### The accumulator (A)

### The quotient register (Q)

### Shifting

### Adding

### Multiplying

### Dividing

## Memory

## Control

## Input / Output

# The software engineering process

## Algorithms

### Calculus / differential equations

### Statistics / Monte Carlo

### Linear algebra / linear equations / eigensystems

## Memory layout

## Assembler / loader

## Run

## Debugging / post-mortem

# The emulator

## Existing emulators

### simh

### SILLIAC

### others

## Why build a new one?

